import {KEY,fresh,seconds,format,parseTime,toggle,score,ordered,valid,migrate,archiveAndNew} from './model.js';
const $=id=>document.getElementById(id);let state=fresh(),editId=null,pendingTime=0,storageBlocked=false;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!valid(parsed))throw Error('invalid');state=migrate(parsed);}}catch{storageBlocked=true;$('storage-status').textContent='Sparad data kunde inte läsas. Ny data skrivs inte över den.';}
function say(text){$('notice').textContent=text;}
function persist(candidate=state){if(storageBlocked)return false;try{localStorage.setItem(KEY,JSON.stringify(candidate));$('storage-status').textContent='Sparas automatiskt på den här enheten';return true;}catch{$('storage-status').textContent='Kunde inte spara. Håll appen öppen för att behålla matchen.';}}
function clock(){const running=state.startedAt!==null;$('clock').textContent=format(seconds(state));$('toggle-clock').textContent=running?'Ⅱ Pausa klockan':seconds(state)>0?'▶ Fortsätt':'▶ Starta klockan';}
function render(){renderHistory();$('match-date').textContent=dateLabel(state.date);document.querySelectorAll('[data-goal]').forEach(b=>{b.querySelector('span').textContent=state.teams[b.dataset.goal].name;});for(const team of ['home','away'])$(team+'-name').textContent=state.teams[team].name;const totals=score(state);$('home-score').textContent=totals.home;$('away-score').textContent=totals.away;$('goal-count').textContent=state.goals.length;$('undo').disabled=!state.goals.length;clock();const log=$('log');log.replaceChildren();if(!state.goals.length){const p=document.createElement('p');p.className='empty';const strong=document.createElement('strong');strong.textContent='Allt börjar med avspark.';p.append(strong,'Tryck på + Mål när bollen går i nät.');log.append(p);return;}const running={home:0,away:0};for(const goal of ordered(state)){running[goal.team]++;const row=document.createElement('button');row.className='event';row.setAttribute('aria-label',`Redigera mål ${format(goal.time)}, ${goal.scorer||'okänd målskytt'}`);const time=document.createElement('time');time.textContent=format(goal.time);const details=document.createElement('span');details.className='details';const name=document.createElement('strong');name.textContent=goal.scorer||'Okänd målskytt';const subtitle=document.createElement('small');subtitle.textContent=state.teams[goal.team].name+' · '+(goal.assist?'Assist: '+goal.assist:'Ingen assist');details.append(name,subtitle);const result=document.createElement('span');result.className='event-score';result.textContent=running.home+'–'+running.away;const arrow=document.createElement('span');arrow.className='edit';arrow.textContent='↗';row.append(time,details,result,arrow);row.onclick=()=>openGoal(goal.team,goal);log.prepend(row);}}
function players(){const list=$('players');list.replaceChildren();for(const p of state.teams[$('goal-team').value].players){const option=document.createElement('option');option.value=p;list.append(option);}}
function openGoal(team,goal){editId=goal?.id||null;pendingTime=goal?.time??seconds(state);$('goal-title').textContent=goal?'Redigera mål':'Registrera mål';for(const option of $('goal-team').options)option.textContent=state.teams[option.value].name;$('goal-team').value=team;$('scorer').value=goal?.scorer||'';$('assist').value=goal?.assist||'';$('no-assist').checked=!goal?.assist;$('assist').disabled=$('no-assist').checked;$('goal-time').value=format(pendingTime);players();$('goal-dialog').showModal();}
document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>openGoal(b.dataset.goal));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('goal-team').onchange=players;$('no-assist').onchange=()=>{$('assist').disabled=$('no-assist').checked;};
$('goal-form').onsubmit=e=>{e.preventDefault();const scorer=$('scorer').value.trim(),assist=$('no-assist').checked?'':$('assist').value.trim();if(!$('no-assist').checked&&!assist){$('assist').setCustomValidity('Ange assist eller välj Ingen assist.');$('assist').reportValidity();return;}if(scorer&&assist&&scorer.toLocaleLowerCase()===assist.toLocaleLowerCase()){$('assist').setCustomValidity('Målskytt och assist måste vara olika spelare.');$('assist').reportValidity();return;}const existing=state.goals.find(g=>g.id===editId);const goal={id:existing?.id||crypto.randomUUID(),createdAt:existing?.createdAt||Date.now(),team:$('goal-team').value,time:parseTime($('goal-time').value),scorer,assist};if(existing)Object.assign(existing,goal);else state.goals.push(goal);persist();render();$('goal-dialog').close();say(existing?'Målet har uppdaterats.':'Målet har registrerats.');};
for(const id of ['assist','scorer','no-assist'])$(id).addEventListener('input',()=> $('assist').setCustomValidity(''));
$('toggle-clock').onclick=()=>{toggle(state);persist();clock();};
$('setup-button').onclick=()=>{$('date-input').value=state.date;for(const k of ['home','away']){$(k+'-input').value=state.teams[k].name;$(k+'-players').value=state.teams[k].players.join('\n');}$('setup-dialog').showModal();};
$('setup-form').onsubmit=e=>{e.preventDefault();for(const k of ['home','away']){const name=$(k+'-input').value.trim();if(!name){$(k+'-input').setCustomValidity('Ange ett lagnamn.');$(k+'-input').reportValidity();return;}}for(const k of ['home','away'])state.teams[k]={name:$(k+'-input').value.trim(),players:[...new Set($(k+'-players').value.split('\n').map(p=>p.trim().slice(0,80)).filter(Boolean))]};state.date=$('date-input').value;persist();render();$('setup-dialog').close();say('Lagen och spelarlistorna är sparade.');};
for(const k of ['home','away'])$(k+'-input').oninput=()=>$(k+'-input').setCustomValidity('');
function confirmAction(title,copy,action){$('confirm-title').textContent=title;$('confirm-copy').textContent=copy;$('confirm-dialog').returnValue='';$('confirm-dialog').onclose=()=>{if($('confirm-dialog').returnValue==='yes')action();};$('confirm-dialog').showModal();}
$('undo').onclick=()=>{const last=state.goals.at(-1);if(!last)return;confirmAction('Ångra senaste mål?',`${state.teams[last.team].name}, ${format(last.time)} – ${last.scorer||'Okänd målskytt'}. Målet tas bort.`,()=>{state.goals.pop();persist();render();say('Senast registrerade målet är borttaget.');});};
$('new-match').onclick=()=>confirmAction('Spara och börja en ny match?','Nuvarande match sparas i matchloggen med datum, resultat och mål. Nästa match får dagens datum. Lag och spelarlistor behålls.',()=>{const next=archiveAndNew(state);if(!persist(next)){say('Matchen kunde inte sparas. Nuvarande match behålls.');return;}state=next;render();say('Matchen är sparad. Redo för nästa avspark!');});
function dateLabel(date){return new Date(date+'T12:00:00').toLocaleDateString('sv-SE',{day:'numeric',month:'long',year:'numeric'});}
function renderHistory(){
 const matches=[...(state.history||[])].sort((a,b)=>b.date.localeCompare(a.date)||b.savedAt-a.savedAt);
 $('history-count').textContent=matches.length+(matches.length===1?' MATCH':' MATCHER');$('history').replaceChildren();
 if(!matches.length){const p=document.createElement('p');p.className='empty';p.textContent='Dina sparade matcher visas här.';$('history').append(p);}
 for(const match of matches){const b=document.createElement('button');b.className='event';const details=document.createElement('span');details.className='details';const title=document.createElement('strong');title.textContent=match.teams.home.name+' – '+match.teams.away.name;const date=document.createElement('small');date.textContent=dateLabel(match.date);details.append(title,date);const result=document.createElement('span');result.className='event-score';const n=score(match);result.textContent=n.home+'–'+n.away;b.append(details,result);b.onclick=()=>showHistory(match);$('history').append(b);}
}
function showHistory(match){
 const n=score(match);$('history-title').textContent=match.teams.home.name+' – '+match.teams.away.name;
 $('history-summary').textContent=dateLabel(match.date)+' · '+n.home+'–'+n.away+' · Matchtid '+format(seconds(match));
 $('history-goals').replaceChildren();const tally={home:0,away:0};
 for(const goal of ordered(match)){tally[goal.team]++;const row=document.createElement('p');row.className='saved-goal';const title=document.createElement('strong');title.textContent=format(goal.time)+' · '+tally.home+'–'+tally.away+' · '+(goal.scorer||'Okänd målskytt');const text=document.createElement('span');text.textContent=match.teams[goal.team].name+' · '+(goal.assist?'Assist: '+goal.assist:'Ingen assist');row.append(title,text);$('history-goals').append(row);}
 if(!match.goals.length)$('history-goals').textContent='Inga mål registrerade.';
 $('history-dialog').showModal();
}

document.addEventListener('visibilitychange',clock);window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const next=JSON.parse(e.newValue);if(valid(next)){state=migrate(next);document.querySelectorAll('dialog[open]').forEach(d=>d.close());render();say('Matchen uppdaterades i ett annat fönster.');}}catch{}}});
render();setInterval(clock,250);
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('offline-status').textContent='✓ Redo att användas offline';}).catch(()=>{$('offline-status').textContent='Offline-stödet kunde inte aktiveras. Öppna appen via HTTPS eller localhost.';});}else $('offline-status').textContent='Offline-stöd kräver en webbläsare med service worker-stöd.';
